export function getLoggingSetter(): () => void;
export function setLoggingForCLI(): void;
export function enableLogging(): void;
export function disableLogging(): void;
export function loggingEnabled(): boolean;
export function error(...args: any[]): void;
export function stop(...args: any[]): void;
export function interrupt(...args: any[]): void;
export function message(...args: any[]): void;
export function warn(...args: any[]): void;
export function warnOnce(...args: any[]): void;
export function setLoggingFunctions(message: any, error: any, stop: any, warn: any): void;
export function getErrorDetail(e: any): string;
export function print(...args: any[]): void;
export function verbose(...args: any[]): void;
export function useVerbose(): any;
export function useDebug(): any;
export function debug(...args: any[]): void;
export function time(slug: any): void;
export function timeEnd(slug: any): void;
export function printError(err: any): void;
export function UserError(msg: any): Error;
export function NonFatalError(msg: any): Error;
export function formatColumns(arr: any, alignments: any): any;
export function formatStringsAsGrid(arr: any, width: any): any;
export function formatLogArgs(args: any): any;
export function logArgs(args: any): void;
export function truncateString(str: any, maxLen: any): any;
